// Original practice questions written for this app, following the IGKO Class 3 topic list.
// Fields: c = chapter id, q = question, o = 4 options, a = index of correct option (0=A … 3=D),
//         e = short explanation, h = true for Achievers/HOTS-style questions.
'use strict';

const CHAPTERS = [
  { id: 1, name: 'Me and My Surroundings', icon: '🏡' },
  { id: 2, name: 'Plants and Animals', icon: '🌱' },
  { id: 3, name: 'India and the World', icon: '🌏' },
  { id: 4, name: 'Science and Technology', icon: '🔬' },
  { id: 5, name: 'Language and Literature', icon: '📚' },
  { id: 6, name: 'Earth and Its Environment', icon: '🌍' },
  { id: 7, name: 'Transport and Communication', icon: '🚆' },
  { id: 8, name: 'Sports', icon: '🏏' },
  { id: 9, name: 'Maths Fun', icon: '🔢' },
  { id: 10, name: 'Life Skills', icon: '🤝' },
  { id: 11, name: 'Current Affairs and Developments', icon: '📰' },
];

const CURRENT_AFFAIRS_AS_OF = 'October 2026';

const BUILTIN_QUESTIONS = [
  // ── Chapter 1: Me and My Surroundings ──
  { c: 1, q: 'How many bones are there in the body of a grown-up person?', o: ['106', '206', '306', '26'], a: 1, e: 'An adult human skeleton has 206 bones.' },
  { c: 1, q: 'Which organ pumps blood to all parts of our body?', o: ['Lungs', 'Stomach', 'Heart', 'Brain'], a: 2, e: 'The heart is a muscle that pumps blood all the time.' },
  { c: 1, q: 'Which sense organ helps us to smell a flower?', o: ['Nose', 'Eyes', 'Ears', 'Tongue'], a: 0, e: 'We smell with our nose.' },
  { c: 1, q: 'Who takes care of our teeth?', o: ['Cardiologist', 'Dentist', 'Plumber', 'Tailor'], a: 1, e: 'A dentist is a doctor for teeth.' },
  { c: 1, q: 'Which festival is known as the "Festival of Lights"?', o: ['Holi', 'Eid', 'Christmas', 'Diwali'], a: 3, e: 'Diwali is celebrated by lighting diyas and lamps.' },
  { c: 1, q: 'Christmas is celebrated every year on', o: ['25 December', '15 August', '2 October', '26 January'], a: 0, e: 'Christmas falls on 25 December.' },
  { c: 1, q: 'Eid-ul-Fitr is celebrated at the end of the holy month of', o: ['Shravan', 'Ramadan', 'Kartik', 'Chaitra'], a: 1, e: 'Eid-ul-Fitr marks the end of the fasting month of Ramadan.' },
  { c: 1, q: 'Which festival is played with colours?', o: ['Onam', 'Pongal', 'Holi', 'Lohri'], a: 2, e: 'Holi is the festival of colours.' },
  { c: 1, q: 'Which is the largest organ of the human body?', o: ['Heart', 'Liver', 'Brain', 'Skin'], a: 3, e: 'The skin covers our whole body and is the largest organ.' },
  { c: 1, q: 'Which number do we dial in India to call the fire brigade?', o: ['100', '101', '108', '1098'], a: 1, e: '101 is the fire service number. 112 is the all-in-one emergency number.' },
  { c: 1, q: 'Your mother\'s mother is your', o: ['Aunt', 'Sister', 'Grandmother', 'Cousin'], a: 2, e: 'Your mother\'s mother is your grandmother (nani).' },
  { c: 1, q: 'Which part of the body helps us to breathe?', o: ['Lungs', 'Kidneys', 'Bones', 'Stomach'], a: 0, e: 'We breathe in air with our lungs.' },
  { c: 1, q: 'Pongal is a harvest festival mainly celebrated in', o: ['Punjab', 'Tamil Nadu', 'Gujarat', 'Assam'], a: 1, e: 'Pongal is the harvest festival of Tamil Nadu.' },
  { c: 1, q: 'How many milk teeth does a child usually have?', o: ['32', '10', '28', '20'], a: 3, e: 'Children have 20 milk teeth. Adults have 32 teeth.' },
  { c: 1, q: 'Which colour of the traffic light tells us to STOP?', o: ['Green', 'Yellow', 'Red', 'Blue'], a: 2, e: 'Red means stop, yellow means get ready, green means go.' },
  { c: 1, q: 'Which of these is a good habit?', o: ['Washing hands before eating', 'Biting nails', 'Throwing litter on the road', 'Sleeping very late'], a: 0, e: 'Washing hands before eating keeps germs away.' },
  { c: 1, q: 'Rearrange the letters to find a person who stitches clothes.', o: ['RIATOL', 'RAMFRE', 'KREBA', 'TOPNASM'], a: 0, e: 'RIATOL → TAILOR. The others make FARMER, BAKER and POSTMAN.', h: true },
  { c: 1, q: 'Select the INCORRECT match.', o: ['Pilot – Flies an aeroplane', 'Carpenter – Makes things from wood', 'Cobbler – Repairs shoes', 'Plumber – Repairs electric wires'], a: 3, e: 'A plumber fixes water pipes. An electrician repairs electric wires.', h: true },
  { c: 1, q: 'How many sense organs does the human body have?', o: ['3', '4', '5', '6'], a: 2, e: 'Eyes, ears, nose, tongue and skin — 5 sense organs.', h: true },

  // ── Chapter 2: Plants and Animals ──
  { c: 2, q: 'Plants make their food in their', o: ['Roots', 'Leaves', 'Flowers', 'Seeds'], a: 1, e: 'Leaves use sunlight, air and water to make food.' },
  { c: 2, q: 'The green colour of leaves is due to', o: ['Chlorophyll', 'Water', 'Oxygen', 'Soil'], a: 0, e: 'Chlorophyll gives leaves their green colour and helps make food.' },
  { c: 2, q: 'Which is the largest animal on Earth?', o: ['Elephant', 'Giraffe', 'Shark', 'Blue whale'], a: 3, e: 'The blue whale is the biggest animal that has ever lived.' },
  { c: 2, q: 'Which is the fastest land animal?', o: ['Horse', 'Cheetah', 'Lion', 'Deer'], a: 1, e: 'A cheetah can run faster than any other land animal.' },
  { c: 2, q: 'The young one of a frog is called a', o: ['Cub', 'Kid', 'Tadpole', 'Calf'], a: 2, e: 'A frog\'s baby is a tadpole, which lives in water.' },
  { c: 2, q: 'Which of these is correctly matched with its home?', o: ['Bee – Kennel', 'Horse – Stable', 'Dog – Hive', 'Lion – Nest'], a: 1, e: 'Horse – stable. A bee lives in a hive, a dog in a kennel and a lion in a den.' },
  { c: 2, q: 'Which of these animals eats only plants?', o: ['Lion', 'Tiger', 'Eagle', 'Cow'], a: 3, e: 'A cow is a herbivore — it eats only plants.' },
  { c: 2, q: 'What is the national animal of India?', o: ['Tiger', 'Lion', 'Elephant', 'Peacock'], a: 0, e: 'The Bengal tiger is India\'s national animal.' },
  { c: 2, q: 'What is the national flower of India?', o: ['Rose', 'Sunflower', 'Lotus', 'Marigold'], a: 2, e: 'The lotus is India\'s national flower.' },
  { c: 2, q: 'Which plant grows well in the desert?', o: ['Lotus', 'Cactus', 'Mango', 'Rose'], a: 1, e: 'A cactus stores water in its thick stem and has spines instead of leaves.' },
  { c: 2, q: 'Which part of a plant takes in water from the soil?', o: ['Leaves', 'Flower', 'Fruit', 'Roots'], a: 3, e: 'Roots absorb water and hold the plant in the soil.' },
  { c: 2, q: 'Which animal can change its colour to match its surroundings?', o: ['Chameleon', 'Rabbit', 'Cat', 'Parrot'], a: 0, e: 'A chameleon changes colour to hide and to show its mood.' },
  { c: 2, q: 'Which bird cannot fly?', o: ['Sparrow', 'Eagle', 'Ostrich', 'Parrot'], a: 2, e: 'The ostrich is too heavy to fly, but it runs very fast.' },
  { c: 2, q: 'Which animal is called the "ship of the desert"?', o: ['Horse', 'Camel', 'Donkey', 'Elephant'], a: 1, e: 'Camels can walk long distances on sand without much water.' },
  { c: 2, q: 'How many legs does an insect have?', o: ['4', '8', '10', '6'], a: 3, e: 'Insects have 6 legs. A spider has 8 legs, so it is not an insect.' },
  { c: 2, q: 'Which insect gives us silk?', o: ['Silkworm', 'Honeybee', 'Ant', 'Butterfly'], a: 0, e: 'Silk comes from the cocoon of the silkworm.' },
  { c: 2, q: 'Which of these vegetables is a root that we eat?', o: ['Potato', 'Spinach', 'Carrot', 'Cauliflower'], a: 2, e: 'Carrot is a root. Potato is a stem, spinach is leaves and cauliflower is a flower.' },
  { c: 2, q: 'Which plant catches and eats small insects?', o: ['Tulsi', 'Pitcher plant', 'Money plant', 'Neem'], a: 1, e: 'The pitcher plant traps insects inside its jug-shaped leaf.', h: true },
  { c: 2, q: 'Some animals sleep through the whole cold winter. This is called', o: ['Migration', 'Camouflage', 'Pollination', 'Hibernation'], a: 3, e: 'Hibernation is a long winter sleep, for example by some bears and frogs.', h: true },
  { c: 2, q: 'Which of these is NOT a mammal?', o: ['Hen', 'Whale', 'Bat', 'Cow'], a: 0, e: 'A hen lays eggs and has feathers — it is a bird. Whales and bats are mammals.', h: true },

  // ── Chapter 3: India and the World ──
  { c: 3, q: 'What is the capital of India?', o: ['Mumbai', 'Kolkata', 'New Delhi', 'Chennai'], a: 2, e: 'New Delhi is the capital of India.' },
  { c: 3, q: 'How many states are there in India?', o: ['25', '28', '29', '31'], a: 1, e: 'India has 28 states and 8 Union Territories.' },
  { c: 3, q: 'What is the capital of Japan?', o: ['Tokyo', 'Beijing', 'Seoul', 'Bangkok'], a: 0, e: 'Tokyo is the capital of Japan.' },
  { c: 3, q: 'The "Yen" is the currency of', o: ['China', 'India', 'Russia', 'Japan'], a: 3, e: 'Japan uses the Yen. China uses the Yuan.' },
  { c: 3, q: 'The Eiffel Tower is in which city?', o: ['London', 'Rome', 'Paris', 'New York'], a: 2, e: 'The Eiffel Tower is in Paris, France.' },
  { c: 3, q: 'The Great Wall is in which country?', o: ['China', 'Egypt', 'India', 'Italy'], a: 0, e: 'The Great Wall of China is thousands of kilometres long.' },
  { c: 3, q: 'Kathakali is a famous dance form of', o: ['Punjab', 'Kerala', 'Assam', 'Rajasthan'], a: 1, e: 'Kathakali comes from Kerala and uses colourful face make-up.' },
  { c: 3, q: 'Pandit Ravi Shankar was famous for playing the', o: ['Tabla', 'Flute', 'Santoor', 'Sitar'], a: 3, e: 'Pandit Ravi Shankar was a world-famous sitar player.' },
  { c: 3, q: 'Which is the smallest state of India by area?', o: ['Sikkim', 'Tripura', 'Goa', 'Kerala'], a: 2, e: 'Goa is the smallest state by area.' },
  { c: 3, q: 'Who wrote India\'s national anthem "Jana Gana Mana"?', o: ['Rabindranath Tagore', 'Bankim Chandra Chatterjee', 'Mahatma Gandhi', 'Sarojini Naidu'], a: 0, e: 'Rabindranath Tagore wrote Jana Gana Mana. "Vande Mataram" was written by Bankim Chandra Chatterjee.' },
  { c: 3, q: 'Which country\'s flag is white with a red circle in the middle?', o: ['China', 'Bangladesh', 'Canada', 'Japan'], a: 3, e: 'Japan\'s flag has a red circle (the Sun) on white. Bangladesh has a red circle on green.' },
  { c: 3, q: 'Pizza and pasta are famous dishes from', o: ['Italy', 'Mexico', 'Japan', 'Egypt'], a: 0, e: 'Pizza and pasta come from Italy.' },
  { c: 3, q: 'Dhokla is a famous snack from', o: ['Bihar', 'Gujarat', 'Kerala', 'Punjab'], a: 1, e: 'Dhokla is a steamed snack from Gujarat.' },
  { c: 3, q: 'How many spokes are there in the Ashoka Chakra on our national flag?', o: ['12', '20', '24', '32'], a: 2, e: 'The navy-blue Ashoka Chakra has 24 spokes.' },
  { c: 3, q: 'Who is called the "Father of the Nation" in India?', o: ['Jawaharlal Nehru', 'Bhagat Singh', 'Subhas Chandra Bose', 'Mahatma Gandhi'], a: 3, e: 'Mahatma Gandhi is called the Father of the Nation.' },
  { c: 3, q: 'Lavani is a folk dance of', o: ['Maharashtra', 'Odisha', 'Manipur', 'Tamil Nadu'], a: 0, e: 'Lavani is a lively folk dance of Maharashtra.' },
  { c: 3, q: 'Select the INCORRECT pair of country and capital.', o: ['Japan – Tokyo', 'France – Paris', 'Australia – Sydney', 'Russia – Moscow'], a: 2, e: 'The capital of Australia is Canberra, not Sydney.', h: true },
  { c: 3, q: 'Which of these monuments is NOT in India?', o: ['Qutub Minar', 'Gateway of India', 'Colosseum', 'Charminar'], a: 2, e: 'The Colosseum is in Rome, Italy.', h: true },
  { c: 3, q: 'I am a white marble monument on the bank of the Yamuna. I was built by Shah Jahan. Where am I?', o: ['Delhi', 'Agra', 'Jaipur', 'Lucknow'], a: 1, e: 'The Taj Mahal is in Agra, Uttar Pradesh.', h: true },

  // ── Chapter 4: Science and Technology ──
  { c: 4, q: 'Who invented the telephone?', o: ['Thomas Edison', 'Alexander Graham Bell', 'Isaac Newton', 'Wright Brothers'], a: 1, e: 'Alexander Graham Bell is known for inventing the telephone.' },
  { c: 4, q: 'Which planet is closest to the Sun?', o: ['Mercury', 'Venus', 'Earth', 'Mars'], a: 0, e: 'Mercury is the closest planet to the Sun.' },
  { c: 4, q: 'Which planet is called the "Red Planet"?', o: ['Jupiter', 'Saturn', 'Mars', 'Neptune'], a: 2, e: 'Mars looks red because of rusty dust on it.' },
  { c: 4, q: 'Which is the largest planet in our solar system?', o: ['Earth', 'Saturn', 'Uranus', 'Jupiter'], a: 3, e: 'Jupiter is the biggest planet.' },
  { c: 4, q: 'How many planets are there in our solar system?', o: ['7', '8', '9', '10'], a: 1, e: 'There are 8 planets. Pluto is now called a dwarf planet.' },
  { c: 4, q: 'Which instrument helps us see faraway stars and planets?', o: ['Microscope', 'Thermometer', 'Telescope', 'Stethoscope'], a: 2, e: 'A telescope makes faraway objects look closer.' },
  { c: 4, q: 'Water freezes into ice at', o: ['0 °C', '10 °C', '50 °C', '100 °C'], a: 0, e: 'Water freezes at 0 °C and boils at 100 °C.' },
  { c: 4, q: 'Which is the natural satellite of the Earth?', o: ['Sun', 'Mars', 'Star', 'Moon'], a: 3, e: 'The Moon goes around the Earth.' },
  { c: 4, q: 'A magnet attracts objects made of', o: ['Wood', 'Iron', 'Plastic', 'Paper'], a: 1, e: 'Magnets pull iron things like nails and pins.' },
  { c: 4, q: 'Which gas do we need to breathe in to stay alive?', o: ['Oxygen', 'Carbon dioxide', 'Nitrogen', 'Smoke'], a: 0, e: 'We breathe in oxygen and breathe out carbon dioxide.' },
  { c: 4, q: 'Which of these is an INPUT device of a computer?', o: ['Monitor', 'Printer', 'Keyboard', 'Speaker'], a: 2, e: 'A keyboard puts information into the computer. The others give output.' },
  { c: 4, q: 'What is the name of India\'s space agency?', o: ['NASA', 'ISRO', 'DRDO', 'BARC'], a: 1, e: 'ISRO is the Indian Space Research Organisation. NASA is America\'s.' },
  { c: 4, q: 'Who was the first Indian to travel to space (in 1984)?', o: ['Kalpana Chawla', 'Sunita Williams', 'A.P.J. Abdul Kalam', 'Rakesh Sharma'], a: 3, e: 'Rakesh Sharma went to space in 1984.' },
  { c: 4, q: 'A thermometer is used to measure', o: ['Weight', 'Temperature', 'Length', 'Time'], a: 1, e: 'A thermometer measures how hot or cold something is.' },
  { c: 4, q: 'Steam is water in which state?', o: ['Solid', 'Liquid', 'Gas', 'None of these'], a: 2, e: 'Ice is solid, water is liquid and steam is gas.' },
  { c: 4, q: 'Which of these does NOT need electricity to work?', o: ['Television', 'Bicycle', 'Refrigerator', 'Ceiling fan'], a: 1, e: 'We pedal a bicycle — it needs no electricity.', h: true },
  { c: 4, q: 'Which of these gives out its OWN light?', o: ['Moon', 'Mirror', 'Sun', 'Planet Earth'], a: 2, e: 'The Sun is a star and makes its own light. The Moon only reflects sunlight.', h: true },
  { c: 4, q: 'Venus is farther from the Sun than Mercury, yet it is the hottest planet. Why?', o: ['It is the biggest planet', 'Its thick clouds trap heat', 'It has many volcanoes only', 'It has no clouds at all'], a: 1, e: 'Venus has a very thick atmosphere that traps heat like a blanket.', h: true },

  // ── Chapter 5: Language and Literature ──
  { c: 5, q: 'What is the opposite of "brave"?', o: ['Strong', 'Bold', 'Coward', 'Kind'], a: 2, e: 'Brave ↔ coward.' },
  { c: 5, q: 'What is the plural of "child"?', o: ['Childs', 'Children', 'Childes', 'Childrens'], a: 1, e: 'One child, many children.' },
  { c: 5, q: 'What is the plural of "mouse"?', o: ['Mice', 'Mouses', 'Mousies', 'Mices'], a: 0, e: 'One mouse, many mice.' },
  { c: 5, q: 'Which word is spelt correctly?', o: ['Beautifull', 'Beutiful', 'Beatiful', 'Beautiful'], a: 3, e: 'B-E-A-U-T-I-F-U-L.' },
  { c: 5, q: 'Which word means the same as "big"?', o: ['Tiny', 'Large', 'Thin', 'Short'], a: 1, e: 'Big and large are synonyms.' },
  { c: 5, q: 'Who wrote the Panchatantra stories?', o: ['Vishnu Sharma', 'Tulsidas', 'Kalidasa', 'Premchand'], a: 0, e: 'The Panchatantra fables are credited to Vishnu Sharma.' },
  { c: 5, q: 'Who wrote the Harry Potter books?', o: ['Roald Dahl', 'Enid Blyton', 'J.K. Rowling', 'Ruskin Bond'], a: 2, e: 'J.K. Rowling wrote the Harry Potter series.' },
  { c: 5, q: 'Who wrote the Ramayana in Sanskrit?', o: ['Ved Vyasa', 'Kalidasa', 'Surdas', 'Valmiki'], a: 3, e: 'Maharishi Valmiki wrote the Ramayana. Ved Vyasa wrote the Mahabharata.' },
  { c: 5, q: 'Mowgli is a character from', o: ['The Jungle Book', 'Cinderella', 'Peter Pan', 'Pinocchio'], a: 0, e: 'Mowgli is from "The Jungle Book" by Rudyard Kipling.' },
  { c: 5, q: 'Fill in the blank: I can ____ the birds singing.', o: ['here', 'hear', 'hair', 'heir'], a: 1, e: '"Hear" is what we do with our ears. "Here" means this place.' },
  { c: 5, q: 'A group of cows is called a', o: ['Swarm', 'Pride', 'Herd', 'Flock'], a: 2, e: 'A herd of cows, a pride of lions, a swarm of bees, a flock of sheep.' },
  { c: 5, q: 'What is the feminine (female) of "king"?', o: ['Princess', 'Lady', 'Duchess', 'Queen'], a: 3, e: 'King → queen. Prince → princess.' },
  { c: 5, q: 'Which word is a NOUN (naming word)?', o: ['Delhi', 'Run', 'Happy', 'Quickly'], a: 0, e: 'Delhi is the name of a place, so it is a noun.' },
  { c: 5, q: 'Complete the phrase: As busy as a ____', o: ['cat', 'bee', 'stone', 'cloud'], a: 1, e: '"As busy as a bee" — bees work all day.' },
  { c: 5, q: 'Birbal was a clever minister in the court of', o: ['Ashoka', 'Shivaji', 'Akbar', 'Krishnadevaraya'], a: 2, e: 'Birbal was in Emperor Akbar\'s court. Tenali Raman was in Krishnadevaraya\'s court.' },
  { c: 5, q: 'Which of these letters is a vowel?', o: ['B', 'K', 'T', 'E'], a: 3, e: 'The vowels are A, E, I, O and U.' },
  { c: 5, q: 'Which word can be made using only the letters of "TEACHER"?', o: ['CHEAT', 'CHAIR', 'PEACH', 'BEACH'], a: 0, e: 'CHEAT uses C, H, E, A, T — all are in TEACHER. CHAIR needs I, PEACH needs P, BEACH needs B.', h: true },
  { c: 5, q: 'Find the odd one out.', o: ['Apple', 'Mango', 'Carrot', 'Banana'], a: 2, e: 'Carrot is a vegetable; the others are fruits.', h: true },
  { c: 5, q: 'In the story, whose nose grew longer every time he told a lie?', o: ['Aladdin', 'Pinocchio', 'Peter Pan', 'Tom Thumb'], a: 1, e: 'Pinocchio\'s nose grew whenever he lied.', h: true },

  // ── Chapter 6: Earth and Its Environment ──
  { c: 6, q: 'Which is the largest ocean in the world?', o: ['Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean', 'Pacific Ocean'], a: 3, e: 'The Pacific Ocean is the largest and deepest ocean.' },
  { c: 6, q: 'Which is the largest continent?', o: ['Asia', 'Africa', 'Europe', 'Australia'], a: 0, e: 'Asia is the largest continent. India is in Asia.' },
  { c: 6, q: 'How many continents are there in the world?', o: ['5', '6', '7', '8'], a: 2, e: 'There are 7 continents.' },
  { c: 6, q: 'Which is the longest river in India?', o: ['Yamuna', 'Ganga', 'Godavari', 'Narmada'], a: 1, e: 'The Ganga is India\'s longest river.' },
  { c: 6, q: 'Which is the largest desert in India?', o: ['Sahara', 'Gobi', 'Kalahari', 'Thar'], a: 3, e: 'The Thar Desert is in Rajasthan.' },
  { c: 6, q: 'World Environment Day is celebrated on', o: ['5 June', '22 April', '14 November', '1 May'], a: 0, e: 'World Environment Day is 5 June. Earth Day is 22 April.' },
  { c: 6, q: 'Which is the highest mountain peak in the world?', o: ['K2', 'Kanchenjunga', 'Mount Everest', 'Nanda Devi'], a: 2, e: 'Mount Everest is the highest peak in the world.' },
  { c: 6, q: 'The three Rs to save our environment are Reduce, Reuse and', o: ['Remove', 'Recycle', 'Repeat', 'Read'], a: 1, e: 'Reduce, Reuse, Recycle.' },
  { c: 6, q: 'The blanket of air around the Earth is called the', o: ['Atmosphere', 'Ocean', 'Crust', 'Core'], a: 0, e: 'The atmosphere is the layer of air around the Earth.' },
  { c: 6, q: 'Which of these will never run out (is renewable)?', o: ['Coal', 'Petrol', 'Natural gas', 'Sunlight'], a: 3, e: 'Sunlight is renewable. Coal, petrol and gas will run out one day.' },
  { c: 6, q: 'Hot melted rock that flows out of a volcano is called', o: ['Sand', 'Lava', 'Ice', 'Mud'], a: 1, e: 'Melted rock coming out of a volcano is lava.' },
  { c: 6, q: 'Which continent is covered with thick ice and has penguins?', o: ['Europe', 'Asia', 'Antarctica', 'Africa'], a: 2, e: 'Antarctica is the icy continent near the South Pole.' },
  { c: 6, q: 'How many colours are there in a rainbow?', o: ['5', '6', '8', '7'], a: 3, e: 'VIBGYOR — 7 colours.' },
  { c: 6, q: 'The Sun rises in the', o: ['East', 'West', 'North', 'South'], a: 0, e: 'The Sun rises in the east and sets in the west.' },
  { c: 6, q: 'How long does the Earth take to spin once on its axis?', o: ['1 hour', '24 hours', '7 days', '365 days'], a: 1, e: 'One spin takes 24 hours (one day). Going once around the Sun takes about 365 days.' },
  { c: 6, q: 'In India, wet kitchen waste like fruit peels should go into the ____ dustbin.', o: ['Blue', 'Red', 'Green', 'Black'], a: 2, e: 'Green bin for wet waste, blue bin for dry waste.' },
  { c: 6, q: 'During an earthquake, what is the safest thing to do indoors?', o: ['Run down the stairs', 'Stand near a glass window', 'Use the lift', 'Get under a strong table and hold on'], a: 3, e: '"Drop, cover and hold on" under a strong table.', h: true },
  { c: 6, q: 'Which of these is NOT a way to save water?', o: ['Closing the tap while brushing', 'Fixing leaking taps', 'Washing the car daily with a running pipe', 'Collecting rainwater'], a: 2, e: 'A running pipe wastes a lot of water.', h: true },
  { c: 6, q: 'Planting more trees helps us because trees', o: ['Give us oxygen', 'Stop soil from washing away', 'Give homes to birds', 'All of these'], a: 3, e: 'Trees do all of these things.', h: true },

  // ── Chapter 7: Transport and Communication ──
  { c: 7, q: 'Which is the fastest means of transport?', o: ['Bus', 'Train', 'Aeroplane', 'Ship'], a: 2, e: 'Aeroplanes are the fastest way to travel long distances.' },
  { c: 7, q: 'Which vehicle runs on rails?', o: ['Train', 'Truck', 'Car', 'Scooter'], a: 0, e: 'Trains run on railway tracks.' },
  { c: 7, q: 'Which of these is used for mass communication (reaching many people at once)?', o: ['Letter', 'Television', 'Postcard', 'Telegram'], a: 1, e: 'TV, radio and newspapers reach many people at the same time.' },
  { c: 7, q: 'India\'s first passenger train ran in 1853 between', o: ['Delhi and Agra', 'Kolkata and Howrah', 'Chennai and Madurai', 'Bombay and Thane'], a: 3, e: 'The first passenger train ran from Bombay (Mumbai) to Thane on 16 April 1853.' },
  { c: 7, q: 'Who flew the first powered aeroplane?', o: ['Wright Brothers', 'Graham Bell', 'Thomas Edison', 'James Watt'], a: 0, e: 'The Wright Brothers flew the first aeroplane in 1903.' },
  { c: 7, q: 'Where should we cross the road?', o: ['Anywhere', 'At a zebra crossing', 'Between parked cars', 'On a bend'], a: 1, e: 'Use the zebra crossing and look both ways.' },
  { c: 7, q: 'The yellow traffic light means', o: ['Go fast', 'Stop and park', 'Get ready / slow down', 'Turn around'], a: 2, e: 'Yellow means get ready to stop or go.' },
  { c: 7, q: 'Braille is a way of reading used by people who', o: ['Cannot hear', 'Cannot walk', 'Cannot speak', 'Cannot see'], a: 3, e: 'Braille uses raised dots that are read by touch. It was invented by Louis Braille.' },
  { c: 7, q: 'How many digits are there in an Indian PIN code?', o: ['6', '4', '5', '8'], a: 0, e: 'An Indian PIN code has 6 digits.' },
  { c: 7, q: 'To send an e-mail, we need', o: ['A stamp', 'Internet', 'A postbox', 'A pigeon'], a: 1, e: 'E-mail travels over the internet.' },
  { c: 7, q: 'Which vehicle is used to send astronauts and satellites into space?', o: ['Helicopter', 'Jet plane', 'Rocket', 'Hot air balloon'], a: 2, e: 'Rockets are powerful enough to go into space.' },
  { c: 7, q: 'Vande Bharat Express is a', o: ['Ship', 'Bus', 'Aeroplane', 'Train'], a: 3, e: 'Vande Bharat Express is a fast, modern Indian train.' },
  { c: 7, q: 'In olden days, which bird was trained to carry messages?', o: ['Pigeon', 'Crow', 'Parrot', 'Sparrow'], a: 0, e: 'Homing pigeons were used to carry messages.' },
  { c: 7, q: 'Which of these does NOT need fuel to move?', o: ['Car', 'Bicycle', 'Bus', 'Motorcycle'], a: 1, e: 'A bicycle moves with pedal power.' },
  { c: 7, q: 'Find the odd one out.', o: ['Bus', 'Car', 'Boat', 'Truck'], a: 2, e: 'A boat moves on water; the others move on roads.', h: true },
  { c: 7, q: 'Rohan wants to talk to his grandmother in another city and also see her face. What should he use?', o: ['Letter', 'Radio', 'Newspaper', 'Video call'], a: 3, e: 'A video call lets you both talk and see each other.', h: true },
  { c: 7, q: 'Which pair is INCORRECT?', o: ['Ship – Water', 'Aeroplane – Air', 'Train – Air', 'Bus – Road'], a: 2, e: 'A train runs on land (rails), not in the air.', h: true },

  // ── Chapter 8: Sports ──
  { c: 8, q: 'How many players are there in a cricket team on the field?', o: ['9', '11', '7', '6'], a: 1, e: 'A cricket team has 11 players on the field.' },
  { c: 8, q: 'A shuttlecock is used in', o: ['Tennis', 'Squash', 'Table tennis', 'Badminton'], a: 3, e: 'Badminton is played with a racket and a shuttlecock.' },
  { c: 8, q: 'How many rings are there in the Olympic symbol?', o: ['5', '4', '6', '7'], a: 0, e: 'The five rings stand for five parts of the world coming together.' },
  { c: 8, q: 'Neeraj Chopra is famous for which sport?', o: ['Shooting', 'Wrestling', 'Javelin throw', 'Boxing'], a: 2, e: 'Neeraj Chopra won Olympic gold in javelin throw at Tokyo 2020.' },
  { c: 8, q: 'P.V. Sindhu plays', o: ['Badminton', 'Tennis', 'Hockey', 'Chess'], a: 0, e: 'P.V. Sindhu is a champion badminton player.' },
  { c: 8, q: 'Viswanathan Anand is a famous', o: ['Cricketer', 'Footballer', 'Swimmer', 'Chess player'], a: 3, e: 'Viswanathan Anand was India\'s first chess Grandmaster.' },
  { c: 8, q: 'Mary Kom is a world champion in', o: ['Running', 'Boxing', 'Cycling', 'Archery'], a: 1, e: 'Mary Kom is a six-time world champion boxer.' },
  { c: 8, q: 'How many players of each team are on the court in kabaddi?', o: ['5', '6', '7', '11'], a: 2, e: 'Each kabaddi team has 7 players on the court.' },
  { c: 8, q: 'Wimbledon is a famous tournament of', o: ['Tennis', 'Golf', 'Football', 'Hockey'], a: 0, e: 'Wimbledon is a tennis championship held in London.' },
  { c: 8, q: 'The Olympic Games are held every', o: ['2 years', '3 years', '5 years', '4 years'], a: 3, e: 'The Summer Olympics are held every 4 years.' },
  { c: 8, q: 'Which city will host the 2028 Summer Olympics?', o: ['Paris', 'Los Angeles', 'Tokyo', 'Brisbane'], a: 1, e: 'Los Angeles (USA) hosts in 2028. Paris hosted in 2024; Brisbane hosts in 2032.' },
  { c: 8, q: 'Milkha Singh, the "Flying Sikh", was famous for', o: ['Swimming', 'Boxing', 'Running', 'Wrestling'], a: 2, e: 'Milkha Singh was a great sprinter (runner).' },
  { c: 8, q: 'National Sports Day in India (29 August) is celebrated on the birthday of', o: ['Sachin Tendulkar', 'Milkha Singh', 'Kapil Dev', 'Major Dhyan Chand'], a: 3, e: 'It honours hockey wizard Major Dhyan Chand.' },
  { c: 8, q: 'Lionel Messi is a famous', o: ['Footballer', 'Cricketer', 'Tennis player', 'Golfer'], a: 0, e: 'Lionel Messi is a footballer from Argentina.' },
  { c: 8, q: 'Which game is NOT played with a ball?', o: ['Cricket', 'Football', 'Badminton', 'Tennis'], a: 2, e: 'Badminton uses a shuttlecock, not a ball.', h: true },
  { c: 8, q: 'Select the INCORRECT match of game and equipment.', o: ['Cricket – Bat', 'Hockey – Stick', 'Tennis – Racket', 'Golf – Paddle'], a: 3, e: 'Golf is played with a club. A paddle is used in table tennis or rowing.', h: true },
  { c: 8, q: 'Which sport has a "checkmate"?', o: ['Carrom', 'Chess', 'Ludo', 'Badminton'], a: 1, e: 'In chess, checkmate means the king is trapped and the game is over.', h: true },

  // ── Chapter 9: Maths Fun ──
  { c: 9, q: '25 + 17 = ?', o: ['32', '42', '41', '52'], a: 1, e: '25 + 17 = 42.' },
  { c: 9, q: 'How many sides does a triangle have?', o: ['3', '4', '5', '6'], a: 0, e: 'Tri means three.' },
  { c: 9, q: 'One dozen means', o: ['10', '6', '20', '12'], a: 3, e: '1 dozen = 12.' },
  { c: 9, q: '9 × 6 = ?', o: ['45', '56', '54', '63'], a: 2, e: '9 × 6 = 54.' },
  { c: 9, q: 'Which shape has no corners?', o: ['Square', 'Circle', 'Triangle', 'Rectangle'], a: 1, e: 'A circle is round and has no corners.' },
  { c: 9, q: 'The Roman numeral X stands for', o: ['5', '10', '50', '100'], a: 1, e: 'I = 1, V = 5, X = 10, L = 50, C = 100.' },
  { c: 9, q: 'How many minutes are there in one hour?', o: ['100', '30', '60', '24'], a: 2, e: '1 hour = 60 minutes.' },
  { c: 9, q: 'What comes next? 2, 4, 6, 8, ____', o: ['10', '9', '12', '16'], a: 0, e: 'Add 2 each time.' },
  { c: 9, q: '100 paise make', o: ['10 rupees', '1 rupee', '50 rupees', '100 rupees'], a: 1, e: '100 paise = ₹1.' },
  { c: 9, q: 'Which is the largest 3-digit number?', o: ['100', '899', '990', '999'], a: 3, e: '999 is the biggest number with 3 digits.' },
  { c: 9, q: 'If today is Monday, what day will it be 3 days later?', o: ['Wednesday', 'Thursday', 'Friday', 'Tuesday'], a: 1, e: 'Tuesday (1), Wednesday (2), Thursday (3).' },
  { c: 9, q: '1 metre = ____ centimetres', o: ['10', '1000', '100', '50'], a: 2, e: '1 m = 100 cm.' },
  { c: 9, q: 'How many faces does a cube have?', o: ['4', '8', '12', '6'], a: 3, e: 'A cube (like a dice) has 6 faces.' },
  { c: 9, q: '45 − 18 = ?', o: ['27', '37', '33', '23'], a: 0, e: '45 − 18 = 27.' },
  { c: 9, q: 'Which of these is an even number?', o: ['13', '15', '18', '21'], a: 2, e: 'Even numbers end in 0, 2, 4, 6 or 8.' },
  { c: 9, q: 'What comes next? 3, 6, 12, 24, ____', o: ['30', '36', '48', '27'], a: 2, e: 'Each number is double the one before: 24 × 2 = 48.', h: true },
  { c: 9, q: 'Riya has 5 boxes with 4 pencils in each. She gives away 6 pencils. How many are left?', o: ['14', '15', '20', '26'], a: 0, e: '5 × 4 = 20 pencils; 20 − 6 = 14.', h: true },
  { c: 9, q: 'How many months of the year have 31 days?', o: ['5', '6', '7', '8'], a: 2, e: 'January, March, May, July, August, October and December — 7 months.', h: true },

  // ── Chapter 10: Life Skills ──
  { c: 10, q: 'Your friend falls down in the playground and gets hurt. What should you do?', o: ['Laugh at them', 'Walk away', 'Help them and tell a teacher', 'Keep playing'], a: 2, e: 'Help a hurt friend and tell a grown-up.' },
  { c: 10, q: 'A stranger offers you chocolate and asks you to come with him. You should', o: ['Go with him', 'Say "No", move away and tell your parents', 'Take the chocolate only', 'Tell him your address'], a: 1, e: 'Never go with strangers. Say no and tell a trusted adult.' },
  { c: 10, q: 'Which is good table manners?', o: ['Talking with food in the mouth', 'Chewing with the mouth closed', 'Grabbing food from others\' plates', 'Playing with food'], a: 1, e: 'Chew with your mouth closed.' },
  { c: 10, q: 'When you make a mistake and hurt someone, you should', o: ['Say sorry', 'Blame someone else', 'Hide', 'Shout'], a: 0, e: 'Saying sorry shows you care.' },
  { c: 10, q: 'Which is the healthiest snack?', o: ['Potato chips', 'Cold drink', 'Candy', 'Fresh fruit'], a: 3, e: 'Fruits give vitamins and energy.' },
  { c: 10, q: 'How many times a day should we brush our teeth?', o: ['Once a week', 'Twice a day', 'Only on Sundays', 'Never'], a: 1, e: 'Brush in the morning and before going to bed.' },
  { c: 10, q: 'About how many hours should a Class 3 child sleep every night?', o: ['2–3 hours', '4–5 hours', '9–11 hours', '15–16 hours'], a: 2, e: 'Children of this age need around 9 to 11 hours of sleep.' },
  { c: 10, q: 'Sharing your toys with others shows that you are', o: ['Kind', 'Lazy', 'Rude', 'Selfish'], a: 0, e: 'Sharing is a kind habit.' },
  { c: 10, q: 'When you feel very angry, a good thing to do is', o: ['Throw things', 'Hit someone', 'Shout loudly', 'Take slow, deep breaths'], a: 3, e: 'Deep breaths help us calm down.' },
  { c: 10, q: 'While playing an online game, someone asks for your home address. You should', o: ['Tell them', 'Not share it and tell your parents', 'Send a photo of your house', 'Share your password too'], a: 1, e: 'Never share personal details online.' },
  { c: 10, q: 'A good way to save money is to', o: ['Spend all of it', 'Put coins in a piggy bank', 'Lose it', 'Give it to strangers'], a: 1, e: 'A piggy bank helps you save little by little.' },
  { c: 10, q: 'When others are speaking, you should', o: ['Interrupt them', 'Listen and wait for your turn', 'Make noise', 'Walk away'], a: 1, e: 'Good listeners wait for their turn to speak.' },
  { c: 10, q: 'Ravi finds a wallet lying in the school corridor. What is the BEST thing to do?', o: ['Keep it', 'Throw it away', 'Give it to a teacher', 'Spend the money'], a: 2, e: 'Hand it to a teacher so it reaches its owner — this is honesty.', h: true },
  { c: 10, q: 'Your team lost a match. What should you do?', o: ['Blame your teammates', 'Cry and refuse to play again', 'Congratulate the winners and practise more', 'Fight with the other team'], a: 2, e: 'Good sportsmanship means accepting results and trying again.', h: true },

  // ── Chapter 11: Current Affairs and Developments (check date in CURRENT_AFFAIRS_AS_OF) ──
  { c: 11, q: 'Who is the President of India (2026)?', o: ['Droupadi Murmu', 'Ram Nath Kovind', 'Pratibha Patil', 'Narendra Modi'], a: 0, e: 'Droupadi Murmu became President in July 2022.' },
  { c: 11, q: 'Who is the Prime Minister of India (2026)?', o: ['Rahul Gandhi', 'Amit Shah', 'Narendra Modi', 'Manmohan Singh'], a: 2, e: 'Narendra Modi began his third term as PM in June 2024.' },
  { c: 11, q: 'The chief guests at India\'s Republic Day parade on 26 January 2026 were leaders of the', o: ['African Union', 'United Nations', 'BRICS group', 'European Union'], a: 3, e: 'Ursula von der Leyen and António Costa, the two top leaders of the European Union, were the chief guests.' },
  { c: 11, q: 'India celebrates National Space Day on 23 August to remember the landing of', o: ['Chandrayaan-3', 'Mangalyaan', 'Aditya-L1', 'Gaganyaan'], a: 0, e: 'Chandrayaan-3 landed on the Moon on 23 August 2023.' },
  { c: 11, q: 'India\'s Aditya-L1 mission was sent to study the', o: ['Moon', 'Sun', 'Mars', 'Ocean'], a: 1, e: 'Aditya means Sun — the mission studies the Sun.' },
  { c: 11, q: 'In 2025, Shubhanshu Shukla became the first Indian astronaut to visit the', o: ['Moon', 'Mars', 'International Space Station', 'Sun'], a: 2, e: 'He flew to the International Space Station on the Axiom-4 mission in June 2025.' },
  { c: 11, q: 'Which country won the ICC Men\'s T20 World Cup in March 2026?', o: ['Australia', 'New Zealand', 'England', 'India'], a: 3, e: 'India beat New Zealand in the final at Ahmedabad on 8 March 2026.' },
  { c: 11, q: 'In November 2025, India\'s women\'s cricket team won its first', o: ['ICC Women\'s ODI World Cup', 'Olympic gold', 'Asia Cup', 'FIFA World Cup'], a: 0, e: 'India beat South Africa in the final on 2 November 2025.' },
  { c: 11, q: 'Which country won the FIFA (football) World Cup 2026?', o: ['Argentina', 'Spain', 'France', 'Brazil'], a: 1, e: 'Spain beat Argentina 1–0 in the final on 19 July 2026.' },
  { c: 11, q: 'The FIFA World Cup 2026 was hosted by USA, Canada and', o: ['Brazil', 'Spain', 'Mexico', 'Japan'], a: 2, e: 'It was the first World Cup held in three countries.' },
  { c: 11, q: 'In which city were the Commonwealth Games 2026 held?', o: ['Glasgow', 'Birmingham', 'Delhi', 'Melbourne'], a: 0, e: 'The 2026 Commonwealth Games were held in Glasgow, Scotland, in July–August 2026. India won 39 medals.' },
  { c: 11, q: 'The Maha Kumbh Mela of 2025 was held at', o: ['Prayagraj', 'Haridwar', 'Nashik', 'Ujjain'], a: 0, e: 'Maha Kumbh 2025 was held at Prayagraj, Uttar Pradesh.' },
  { c: 11, q: 'The Chenab Rail Bridge, the world\'s highest railway arch bridge, is in', o: ['Himachal Pradesh', 'Jammu and Kashmir', 'Uttarakhand', 'Sikkim'], a: 1, e: 'It was opened in June 2025 in Jammu and Kashmir.' },
  { c: 11, q: 'The new Pamban Bridge, India\'s first vertical-lift sea bridge, connects the mainland to', o: ['Andaman Islands', 'Goa', 'Rameswaram', 'Lakshadweep'], a: 2, e: 'It links Rameswaram island in Tamil Nadu; it opened in April 2025.' },
  { c: 11, q: 'The 2026 Asian Games were held in', o: ['India', 'China', 'South Korea', 'Japan'], a: 3, e: 'They were held in Aichi–Nagoya, Japan.', h: true },
  { c: 11, q: 'At Glasgow 2026, she became the first Indian to win gold at three Commonwealth Games in a row. Who is she, and what is her sport?', o: ['P.V. Sindhu – Badminton', 'Mirabai Chanu – Weightlifting', 'Mary Kom – Boxing', 'Manu Bhaker – Shooting'], a: 1, e: 'Mirabai Chanu won her third straight Commonwealth gold in weightlifting.', h: true },
  { c: 11, q: 'Vyommitra, a robot that looks like a human, is being sent into space in India\'s uncrewed test flight for which mission?', o: ['Chandrayaan', 'Mangalyaan', 'Gaganyaan', 'Aditya-L1'], a: 2, e: 'Gaganyaan is India\'s human spaceflight programme. Its first uncrewed test flight (G1) carries Vyommitra.', h: true },
];
